### ISSUE TITLE
does not work with media

### ISSUE THREAD

**Issue by copyhold** [zgreen/postcss-critical-css#2]
Proof here

git@github.com:copyhold/postcss-critical-css.git

**Comment by zgreen** [comment]
Hey, thanks for the bug report. I'll take a look.

**Comment by zgreen** [comment]
Confirmed. I've got it fixed in https://github.com/zgreen/postcss-critical-css/tree/at-rules, which I hope to have merged soon.

**Comment by zgreen** [comment]
@copyhold I've merged a fix; install the latest version and test it out if you want—thanks!

**Comment by copyhold** [comment]
Cool, it worked. Thank you
