### ISSUE TITLE
2 main problems with @critical{} and critical-selector: this;

### ISSUE THREAD

**Issue by awacode21** [zgreen/postcss-critical-css#21]
Dear Zach Green,

There are 2 major problems with this postcss-critical-css plugin, which makes it useless at the moment.

<s>**First:**

when you use **@critical {}** around your css classes you get a versioning problem with the following error:
`Your current PostCSS version is 5.2.5, but postcss-critical uses 6.0.9. Perhaps this is the source of the error below.
Fatal error: Cannot set property 'parent' of undefined`

Fact here is, my postcss version is 6.0.9 so the latest one. But it throws this error. I guess it is a weird dependency issue within the plugin? I ensured that it is not only a problem on my machine. I asked two other big web projects which also are working with your plugin and facing the same issue. We all three have completely different code base.</s>

**Second:**

When using **critical-selector: this,** and the decision not to minify the output (for example, if you want to do other things with the code before you have it over another tool minified), the critical css classes are written **5 times** into the output file. So there is a huge amount of duplicated code.

Your plugin is a great thing and we really would like to use it, but at the moment it is simply not working right.

We would be very, very happy if that can be fixed.

Best Regards, Annick

**Comment by zgreen** [comment]
Thanks for the bug report, I'll take a look.

**Comment by zgreen** [comment]
@awacode21 Can you paste your `package.json`, and the code that calls postcss with postcss-critical-css?

**Comment by awacode21** [comment]
@zgreen thanks so much for your quick reply. For some reason i guess i got the versioning problem fixed? I updated all occurances of postcss plugins and grunt-postcss and now the first problem seems to work again. What still is not working well is the **critical-selector: this** selector.
When using it that way:
`html {
    critical-selector: this;

    @include background-pattern;
    background-color: $color__primary--beige;
    min-height: 100%;
}`

it ends up in generating:
`

html {
  background-image: url("/images/layout/background-muster.png");
  background-repeat: repeat;
  background-color: #f5f3ef;
  min-height: 100%; }

html {
  background-image: url("/images/layout/background-muster.png");
  background-repeat: repeat;
  background-color: #f5f3ef;
  min-height: 100%; }

html {
  background-image: url("/images/layout/background-muster.png");
  background-repeat: repeat;
  background-color: #f5f3ef;
  min-height: 100%; }

html {
  background-image: url("/images/layout/background-muster.png");
  background-repeat: repeat;
  background-color: #f5f3ef;
  min-height: 100%; }

html {
  background-image: url("/images/layout/background-muster.png");
  background-repeat: repeat;
  background-color: #f5f3ef;
  min-height: 100%; }`

My package.json is:
`{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "author": "",
  "scripts": {
    "start": "grunt build serveContent"
  },
  "buildFolder": "wwwroot",
  "sourceFolder": "StaticResources",
  "dependencies": {
    "assemble-related-pages": "0.0.4",
    "autoprefixer": "6.3.3",
    "browserslist": "^1.5.2",
    "grunt": "^1.0.1",
    "grunt-assemble": "^0.5.0",
    "grunt-cli": "1.2.0",
    "grunt-concurrent": "2.3.1",
    "grunt-contrib-clean": "1.0.0",
    "grunt-contrib-connect": "0.11.2",
    "grunt-contrib-copy": "1.0.0",
    "grunt-contrib-uglify": "^2.0.0",
    "grunt-contrib-watch": "1.0.0",
    "grunt-css-mqpacker": "3.0.1",
    "grunt-cssnano": "2.1.0",
    "grunt-eol": "^1.1.3",
    "grunt-newer": "1.2.0",
    "grunt-postcss": "^0.8.0",
    "grunt-sass": "^2.0.0",
    "grunt-svgmin": "^4.0.0",
    "grunt-svgstore": "^1.0.0",
    "grunt-ts": "6.0.0-beta.15",
    "handlebars-helper-compose": "^0.2.12",
    "handlebars-helpers": "^0.7.7",
    "jit-grunt": "0.10.0",
    "kss": "^3.0.0-beta.17",
    "load-grunt-config": "0.19.2",
    "postcss": "^6.0.9",
    "postcss-critical-css": "^3.0.0",
    "postcss-font-magician": "^2.0.0",
    "postcss-reporter": "^5.0.0",
    "postcss-scss": "^1.0.2",
    "postcss-svg-fragments": "^2.2.0",
    "requirejs": "^2.3.3",
    "stylelint": "7.5.0",
    "time-grunt": "1.4.0"
  },
  "devDependencies": {
    "grunt-kss": "^5.0.1",
    "typescript": "^2.4.1"
  }
}
`

and plugin configuration is:
`processCss: {
        options: {
            syntax: require('postcss-scss'),
            failOnError: true,
            failOnWarning: true,
            map: false,
            processors: [
                require('postcss-reporter')(),
                require("css-mqpacker")({
                    sort: true
                }),
                require('postcss-svg-fragments')(),
                require('postcss-critical-css')({
                    outputPath: 'wwwroot/css',
                    outputDest: 'critical.css',
                    preserve: false,
                    minify: false
                  }),
                require('cssnano')({
                    autoprefixer: {
                        add: true,
                        browsers: ['last 3 versions', '> 1%', 'ie 9']
                    },
                    discardComments: {removeAll: true},
                    discardDuplicates: false,
                    discardUnused: {fontFace: false},
                    minifyFontValues: false,
                    normalizeUrl: false,
                    reduceInitial: false
                })
            ]
        },
        src: ["<%= package.buildFolder %>/css/**/*.css"]
    }`

**Comment by awacode21** [comment]
One thing i recognize on console is the message:
<img width="362" alt="bildschirmfoto 2017-08-23 um 13 56 55" src="https://user-images.githubusercontent.com/30939926/29614573-ea91a800-880a-11e7-84f9-d706143a164f.png">
i don't know if this is important, but maybe it is somehow related to the problem

**Comment by zgreen** [comment]
Confirmed there's a bug here. It's specific to setting `minify: false`, as you noted.

**Comment by zgreen** [comment]
Yeah, I'll see what I can do. Opened a branch with the failing test here: https://github.com/zgreen/postcss-critical-css/tree/21/bug/multiplied-output

**Comment by zgreen** [comment]
@awacode21 @Teun87 latest release should fix this issue; give it a go if you like. Cheers.
