### ISSUE TITLE
Use in conjunction with CSS Modules

### ISSUE THREAD

**Issue by babipal** [zgreen/postcss-critical-css#23]
I'm trying to use this in a React project that also uses CSS Modules and Webpack for the build. I got the plugin to work, only problem is PostCSS is executed in the build chain before CSS modules. So in my critical.css file I'm seeing a rule for .tooltip instead of the CSS Modules namespaced .Tooltip__tooltip___1E4DA. I'd like to run CSS Modules first to get the dynamic class names, but still retain the critical atRules, and then run the postcss-critical-css plugin on the complied CSS. 

Is this possible?

**Comment by zgreen** [comment]
Hmm. A couple ideas come to mind:

1. You could run `postcss-critical-css` inside [`postcss-loader`](https://github.com/postcss/postcss-loader) with [`enforce: 'post'`](https://webpack.js.org/configuration/module/#rule-enforce). This would allow you to keep any other PostCSS plugins running before CSS Modules.

2. You could run CSS Modules as a PostCSS plugin using [`postcss-modules`](https://github.com/css-modules/postcss-modules) or the [`postcss-icss-*` plugins](https://github.com/css-modules?utf8=%E2%9C%93&q=postcss-icss&type=&language=).

Does either of those work for you?
