### ISSUE TITLE
Move postcss to peerDependencies

### ISSUE THREAD

**Issue by stalniy** [zgreen/postcss-critical-css#28]
`postcss-critical-css` is a plugin for `postcss` thus should include `postcss` as `peerDependency` and not as `depedency` in package.json. This basically allows to use whatever supported version of postcss together with the plugin and be sure that different postcss plugins use the same instance of postcss.

Please read this article https://nodejs.org/en/blog/npm/peer-dependencies/ for more details.

I can create a PR if you are ok

**Comment by stalniy** [comment]
Related https://github.com/csstools/postcss-preset-env/issues/65

**Comment by zgreen** [comment]
Hi, thanks for opening this issue.

I agree that is seems like using `peerDependencies` is a better approach. However, it also seems like virtually all of the postcss plugins out there list `postcss` as a `dependency` and not a `peerDependency`. I'm inclined to side with convention in this case. Curious to see what else @ai might have to say about it in the thread you've referenced.

**Comment by zgreen** [comment]
Thanks :)

I'm going to leave `postcss` as a dependency. Closing the issue, but if folks have follow-up thoughts or additional questions etc., feel free to continue to comment.

**Comment by stalniy** [comment]
@ai having it in dependencies hides complexity of managing peerDependencies but it also may hide bugs because different plugins are using different versions. Also it increases resulting node_modules folder (what may be relevant for container envs) and time to install deps, again because of multiple versions.

Frankly speaking, I don't understand this:
> Often requires non-obvious actions from user

```sh
npm i postcss postcss-critical-css
```
In such case, if `postcss` and `postcss-critical-css` are not compatible npm will tell you this. Currently it doesn't. So, people use different plugins with different postcss versions. I found out this just because of strange warning :)

My setup

```sh
 find node_modules/ -name postcss | wc -l
100
```
**100!** instances of postcss with only several plugins:

```js
    "cssnano": "^4.0.5",
    "postcss-cli": "^6.0.0",
    "postcss-critical-css": "^3.0.1",
    "postcss-extend": "^1.0.5",
    "postcss-import": "^12.0.0",
    "postcss-mixins": "^6.2.0",
    "postcss-preset-env": "^5.2.3",
    "postcss-reporter": "^6.0.0",
    "postcss-sprites": "^4.2.1",
```

**Comment by stalniy** [comment]
not every plugin developer keeps package up to date with the latest postcss... Unfortunately.

**Comment by ai** [comment]
@stalniy Why do you have 100 instances of PostCSS? npm and yarn can dedupe dependencies. In your case, you should have only few inctances (PostCSS 6 and PostCSS 7, maybe PostCSS 5).

**Comment by stalniy** [comment]
For some reason `npm` didn't do it try my package.json:

I removed my `package-lock` and reinstalled everything, almost the same stuff:

```sh
find node_modules/ -name postcss -type d | wc -l
97

$ npm -v
6.1.0
$ node -v
v10.5.0
```

My package.json:

```json
{
  "name": "ruba4ok",
  "version": "1.0.0",
  "description": "skin for ruba4ok.com",
  "author": "Sergii Stotskyi",
  "license": "ISC",
  "engines": {
    "node": ">=6.0.0"
  },
  "scripts": {
    "compile.css": "postcss --config tools/postcss.config ./${SKIN:-default}/css/*.pcss --dir ./${SKIN:-default}/css --ext css",
    "minify.js": "find ../../../../media/js -name *.js ! -name *.min.js -exec bash -c 'uglifyjs \"$1\" -c -m --keep-fnames -r \\$super --screw-ie8 --source-map \"${1/.js/.min.js}.map\" -o \"${1/.js/.min.js}\"' _ {} \\;"
  },
  "devDependencies": {
    "cssnano": "^4.0.5",
    "postcss-cli": "^6.0.0",
    "postcss-critical-css": "^3.0.1",
    "postcss-extend": "^1.0.5",
    "postcss-import": "^12.0.0",
    "postcss-mixins": "^6.2.0",
    "postcss-preset-env": "^5.2.3",
    "postcss-reporter": "^6.0.0",
    "postcss-sprites": "^4.2.1",
    "uglify-js": "^2.8.22"
  },
  "dependencies": {
    "nouislider": "^11.1.0"
  }
}
```

**Comment by ai** [comment]
Are you sure that `-name` means exactly the same name and do not contain the part of the name?

**Comment by stalniy** [comment]
@ai I'm sure. If you try to type something like this:

```
find node_modules/ -name postcs -type d 
```

it returns nothing.

**Comment by stalniy** [comment]
However:

```sh
find node_modules/ -name postcs\* -type d | wc -l
199
```

**Comment by stalniy** [comment]
Another article explaining why and when it’s important to use peer deps https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/
