### ISSUE TITLE
Integrate renovate app

### ISSUE THREAD

**Issue by stalniy** [zgreen/postcss-critical-css#29]
Renovate github app helps to keep your dependencies up to date. Check it here https://renovatebot.com/ I can create PR if you are ok.

I want you to upgrade:
* cssnano to 4.x
* postcss to 7.x

**Comment by stalniy** [comment]
renovate updates not only deps but also devDeps & peerDeps. So, I don't see the reason why don't you want to press few buttons and automate dependency updates, it's free :)

**Comment by zgreen** [comment]
Yeah, it looks like a great app :)

Mostly I'm skeptical about adding a third-party thing that has write permissions to the repo. I can see where something like that would be helpful for a project that had a large number of dependencies. BUt this is a small project, and it's easy for me to update the dependencies without offloading that to a services that might go down, get hacked, increase its prices, etc.

I'm gonna leave this issue open for now; if other folks would like to see it integrated, please upvote.

**Comment by stalniy** [comment]
Sceptical? :D

You said it’s easy to update dependencies. It took 30 days for you to accept my PR which updates dependencies (https://github.com/zgreen/postcss-critical-css/pull/31). It doesn’t look easy :D

Anyway thanks for the plugin and all this situation! It was a motivation to write my own plugin for webpack which does the same thing

**Comment by raulferras** [comment]
I personally don't think automatically updating dependencies is a safe move. 
Not all projects follow semantic version and the build could break at any moment easily.

**Comment by stalniy** [comment]
That’s why you need tests :)

**Comment by zgreen** [comment]
This repo now uses Github's [dependabot](https://github.com/apps/dependabot), and while I don't love it, it seems to work well enough for the issue raised here. There wasn't much interest in this issue either way. I'm going to close this; if folks have separate or new dependency-related issues, please open an new one. Thanks.
