### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by bitfella** [zgreen/postcss-critical-css#44]
Hello,
seems like this plugin can't create subfolders when it outputs files. It yelds the following error in console:

```
{ Error: ENOENT: no such file or directory, open 'C:\Web\Project\Content\Store\Critical\subhome.css'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Web\\Project\\Content\\Store\\Critical\\subhome.css' }
```

If subfolders are yet there instead, it writes files correctly. 

This is my configuration:

- Windows 10
- Node 10.0.0, NPM 6.11.3
- Webpack 4.39.3, PostCSS 7.0.17, postcss-critical-css 3.0.4

and this is a snippet of my webpack configuration:

```
{
          test: /\.(css|s[ac]ss)$/i,
          exclude: /node_modules/,
          use: [
            MiniCssExtractPlugin.loader,
            { loader: 'css-loader' },
            {
              loader: 'postcss-loader',
              options: {
                ident: 'postcss',
                plugins: () => [
                  PostcssImport(),
                  PostcssPresetEnv({
                    browsers: 'last 2 versions',
                  }),
                  PostcssCriticalCss({
                    outputPath: path.join(__dirname, 'Content', 'Store', 'Critical')
                    outputDest: 'critical.css',
                    preserve: false,
                    minify: !isDevelopment
                  })
                ]
              }
            },
            { loader: 'sass-loader' }
          ],
        },
```

In the above snippet, "Store" folder is already present in filesystem, while "Critical" folder is not. Anyway the issue happens also when you set subfolders paths in scss files via "critical" at-rule.

If you switch to [fs-extra](github.com/jprichardson/node-fs-extra) instead of fs and [outputFile](github.com/jprichardson/node-fs-extra/blob/master/docs/outputFile.md) in "writeCriticalFile" function instead of writeFile, everything works fine.

Thanks

**Comment by zgreen** [comment]
+1 for `fs-extra`. PRs welcome, but if nothing comes in I'll include this in the next release. Cheers.

**Comment by zgreen** [comment]
Fixed by https://github.com/zgreen/postcss-critical-css/pull/45/files
