### ISSUE TITLE
[TypeError: Cannot read property 'start' of undefined]

### ISSUE THREAD

**Issue by copyhold** [zgreen/postcss-critical-css#7]
**lib/getCriticalRules.js:43**
_b.source_ and _a.source_ are sometimes _undefiened_.
Unfortunately can't provide the test case for that, but adding  
`
          if (!b.source) return 1;
          if (!a.source) return -1;`
before IF solves the issue

**Comment by TomFranssen** [comment]
I'm also experiencing this issue using: critical-selector: scope;

**Comment by zgreen** [comment]
Okay, thanks for the reports. That feature definitely needs more tests; I'll look into it.

**Comment by zgreen** [comment]
@copyhold or @TomFranssen can either of you provide the CSS you've used that throws this error? Thanks.

**Comment by copyhold** [comment]
HTH

        // Ensure source ordering is correct.
        critical[dest] = critical[dest].sort(function (a, b) {
          if (!a.source) console.log('AAAAA', a)
          if (!b.source) console.log('BBBBB', b)
          return a.source.start.line - b.source.start.line;
        });

the result was:
```
BBBBB AtRule {
  raws: {},
  name: 'media',
  params: 'screen and (max-width: 1179px)',
  type: 'atrule',
  nodes: 
   [ Rule {
       raws: {},
       type: 'rule',
       nodes: [Object],
       source: [Object],
       selector: 'header.top .menu',
       lastEach: 2,
       indexes: {},
       parent: [Circular] } ] }
[TypeError: Cannot read property 'start' of undefined]

```

**Comment by zgreen** [comment]
@copyhold I'm happy to dig into this if you can provide the CSS you're using that throws the error. Thanks!

**Comment by copyhold** [comment]
finally found , seems it's a @media + `  critical-selector: scope;`
```
header.top {
  critical-selector: scope;
  background: red;
}
@media screen and (max-width: 400px) {
  header.top {
    width: 100%;
  }
}
```

**Comment by zgreen** [comment]
Awesome. I'll add a test and take a look—thanks!

**Comment by zgreen** [comment]
Resolved by https://github.com/zgreen/postcss-critical-css/pull/13
